apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxlamp
  namespace: development
spec:
  selector:
    matchLabels:
      app: lamp
  replicas: 1
  template:
    metadata:
      labels:
        app: lamp
    spec:
      containers:
      - name: lamp
        image: mattrayner/lamp:latest-1604-php5
        ports:
        - containerPort: 80
