apiVersion: v1
kind: Pod
metadata:
  labels:
    test: healtcheckv
  name:  healtcheckv
spec:
  containers:
  - name: healtcheck
    image: alpine:3.5
    args:
    - /bin/sh
    - -c
    - sleep 12; touch /tmp/healthy; sleep 10; rm -rf /tmp/healthy; sleep 60
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 15
      periodSeconds: 5
